version: "3.9"

services:

  front:
    build: .
    container_name: front
    volumes:
      - '.:/app'
      - '/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true
    labels:
      - traefik.http.routers.front.rule=Host(`front.test.com`)
    ports:
      - 3000:3000
